# Generated by Django 3.1.7 on 2021-04-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assetOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('asset_num', models.IntegerField(choices=[('BOOKED_ASSET', 'ASSET NUMBER IS ALREADY PRESENT'), ('BOOKED_TYPE', 'ASSET TYPE IS ALREADY PRESENT')])),
                ('asset_type', models.CharField(choices=[('BOOKED_ASSET', 'ASSET NUMBER IS ALREADY PRESENT'), ('BOOKED_TYPE', 'ASSET TYPE IS ALREADY PRESENT')], max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
    ]
