# Generated by Django 2.2.10 on 2021-06-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup_details',
            name='lab_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
