# Generated by Django 2.2.10 on 2021-05-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset_details',
            old_name='Owner',
            new_name='asset_id',
        ),
    ]
