# Generated by Django 2.2.10 on 2021-05-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210527_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset_details',
            old_name='asset_id',
            new_name='Owner',
        ),
    ]
