# Generated by Django 2.2.10 on 2021-05-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210527_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup_details',
            name='FQDN',
            field=models.CharField(default='si-z0z15.st.de.bosch.com', max_length=50),
        ),
    ]
